"""Centralized constants for Sylas.

This is the single source of truth for all shared configuration values.
Import from here instead of duplicating across modules.
"""

from pathlib import Path

# Version - single source of truth
__version__ = "1.0.0"

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.resolve()
DEFAULT_REPORT_DIR = None  # Reports go in target project root by default
DEFAULT_CONFIG_PATH = "configs/agent_config.yaml"

# Default exclude patterns for file scanning (test fixtures, build artifacts)
DEFAULT_EXCLUDE_PATTERNS = ["/bad/", "/good/", "/.git/", "/__pycache__/"]

# Protected project directories (never delete/modify root-level)
PROTECTED_PROJECT_DIRS = {
    ".git",
    "agent",
    "configs",
    "tests",
    "tools",
    "mini-projects",
    ".github",
    "__pycache__",
}

# Allowed temporary directories for deletion
ALLOWED_DELETE_DIRS = {"temp", "tmp", "clones", "clone", ".cache"}

# Bandit test IDs to skip by default (false positives or non-critical)
DEFAULT_BANDIT_SKIP_IDS = {"B404", "B603", "B607"}

# GitHub defaults
DEFAULT_GITHUB_API_BASE = "https://api.github.com"
PROTECTED_BRANCHES = {"main", "master", "develop"}
DEFAULT_PR_TARGET_BRANCH = "main"
DEFAULT_REMEDIATION_BRANCH = "remediation-fix"

# Gitleaks
GITLEAKS_INSTALL_URL = "https://github.com/gitleaks/gitleaks/releases"

# Timeouts (seconds)
SCAN_TIMEOUT = 300
SHORT_TIMEOUT = 10
MEDIUM_TIMEOUT = 30
TEST_TIMEOUT = 120
GIT_TIMEOUT = 120
CLONE_TIMEOUT = 120
API_TIMEOUT = 30

# Retry configuration
DEFAULT_MAX_RETRIES = 3

# Scanner names
SCANNER_BANDIT = "bandit"
SCANNER_PIP_AUDIT = "pip-audit"
SCANNER_SEMGREP = "semgrep"
SCANNER_TRIVY = "trivy"
SCANNER_GITHUB = "github"
SCANNER_GITLEAKS = "gitleaks"

# Severity levels
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_HIGH = "HIGH"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_LOW = "LOW"
SEVERITY_UNKNOWN = "UNKNOWN"

# Semgrep vulnerability type mappings (short_name -> vuln_type)
SEMGREP_TYPE_MAPPINGS = {
    "sql_injection": "sql_injection",
    "sql": "sql_injection",
    "sqli": "sql_injection",
    "sql-injection": "sql_injection",
    "sql_query": "sql_injection",
    "sql-query": "sql_injection",
    "raw_sql": "sql_injection",
    "raw-sql": "sql_injection",
    "sqlalchemy": "sql_injection",
    "django-sql": "sql_injection",
    "django-sqli": "sql_injection",
    "django.raw_sql": "sql_injection",
    "django-database": "sql_injection",
    "database-backend": "sql_injection",
    "jdbc": "sql_injection",
    "jpa": "sql_injection",
    "hibernate": "sql_injection",
    "nosql": "sql_injection",
    "mongodb": "sql_injection",
    "mysql": "sql_injection",
    "postgres": "sql_injection",
    "django-no-csrf-token": "django-no-csrf-token",
    "django.csrf": "django-no-csrf-token",
    "csrf": "django-no-csrf-token",
    "csrf-token": "django-no-csrf-token",
    "django.xss": "xss",
    "django.security": "default",
    "django": "default",
    "django-template": "xss",
    "django-template-html": "xss",
    "django-model": "default",
    "django-orm": "sql_injection",
    "django-extra": "sql_injection",
    "django-annotate": "sql_injection",
    "django-request": "default",
    "django-response": "default",
    "django-http-response": "xss",
    "django-mark-safe": "xss",
    "django-format-html": "xss",
    "django-allow-tag": "xss",
    "django-custom-tag": "xss",
    "django-custom-filter": "xss",
    "xss": "xss",
    "cross-site-scripting": "xss",
    "cross-site": "xss",
    "reflected-xss": "xss",
    "reflected_xss": "xss",
    "stored-xss": "xss",
    "stored_xss": "xss",
    "dom-xss": "xss",
    "dom_xss": "xss",
    "js-xss": "xss",
    "react-xss": "xss",
    "angular-xss": "xss",
    "vue-xss": "xss",
    "jinja2": "xss",
    "jinja2-template": "xss",
    "flask-xss": "xss",
    "flask-jinja2": "xss",
    "template": "xss",
    "template-injection": "xss",
    "template-escape": "xss",
    "safe-methods": "xss",
    "mark-safe": "xss",
    "safe-filter": "xss",
    "autoescape": "xss",
    "format-html": "xss",
    "formathtml": "xss",
    "hardcoded": "hardcoded_secret",
    "hardcoded-secret": "hardcoded_secret",
    "hardcoded-credentials": "hardcoded_secret",
    "hardcoded-password": "hardcoded_secret",
    "hardcoded-api-key": "hardcoded_secret",
    "hardcoded-apikey": "hardcoded_secret",
    "hardcoded-bearer": "hardcoded_secret",
    "hardcoded-token": "hardcoded_secret",
    "hardcoded-jwt": "hardcoded_secret",
    "hardcoded-oauth": "hardcoded_secret",
    "hardcoded-aws": "hardcoded_secret",
    "hardcoded-ssh": "hardcoded_secret",
    "hardcoded-db": "hardcoded_secret",
    "hardcoded-database": "hardcoded_secret",
    "hardcoded-connection-string": "hardcoded_secret",
    "secret": "hardcoded_secret",
    "password": "hardcoded_secret",
    "api-key": "hardcoded_secret",
    "apikey": "hardcoded_secret",
    "api-key-hardcoded": "hardcoded_secret",
    "jwt": "hardcoded_secret",
    "oauth": "hardcoded_secret",
    "aws-key": "hardcoded_secret",
    "aws_secret": "hardcoded_secret",
    "private-key": "hardcoded_secret",
    "private_key": "hardcoded_secret",
    "ssh-key": "hardcoded_secret",
    "connection-string": "hardcoded_secret",
    "env-var": "hardcoded_secret",
    "env_var": "hardcoded_secret",
    "environment-variable": "hardcoded_secret",
    "missing-integrity": "missing-integrity",
    "integrity": "missing-integrity",
    "sri": "missing-integrity",
    "subresource-integrity": "missing-integrity",
    "subresource_integrity": "missing-integrity",
    "request-with-http": "request-with-http",
    "http": "request-with-http",
    "http-url": "request-with-http",
    "http-request": "request-with-http",
    "http-get": "request-with-http",
    "http-post": "request-with-http",
    "insecure-http": "request-with-http",
    "clear-text": "request-with-http",
    "cleartext": "request-with-http",
    "ssl": "request-with-http",
    "tls": "request-with-http",
    "https": "request-with-http",
    "avoid_using_app_run_directly": "avoid_using_app_run_directly",
    "app-run": "avoid_using_app_run_directly",
    "app-run-security": "avoid_using_app_run_directly",
    "flask-debug": "avoid_using_app_run_directly",
    "flask": "default",
    "flask-security": "default",
    "flask-unsafe": "default",
    "fastapi": "default",
    "path-traversal": "path_traversal",
    "path_traversal": "path_traversal",
    "directory-traversal": "path_traversal",
    "directory_traversal": "path_traversal",
    "path-traversal-join": "path_traversal",
    "file-path": "path_traversal",
    "filepath": "path_traversal",
    "file-access": "path_traversal",
    "file-read": "path_traversal",
    "file-write": "path_traversal",
    "file-upload": "path_traversal",
    "zip-slip": "path_traversal",
    "command-injection": "command_injection",
    "command_injection": "command_injection",
    "os-injection": "command_injection",
    "os_injection": "command_injection",
    "os-command": "command_injection",
    "shell-injection": "command_injection",
    "shell_injection": "command_injection",
    "subprocess": "command_injection",
    "subprocess-shell": "command_injection",
    "subprocess-with-shell": "command_injection",
    "popen": "command_injection",
    "os-system": "command_injection",
    "os-exec": "command_injection",
    "os-popen": "command_injection",
    "code-exec": "command_injection",
    "arbitrary-command": "command_injection",
    "dangerous-spawn": "command_injection",
    "ssrf": "ssrf",
    "server-side-request-forgery": "ssrf",
    "server_side_request_forgery": "ssrf",
    "request-forgery": "ssrf",
    "url-fetch": "ssrf",
    "open-redirect-ssrf": "ssrf",
    "dangerous-request": "ssrf",
    "requests": "ssrf",
    "urllib": "ssrf",
    "httpx": "ssrf",
    "aiohttp": "ssrf",
    "xxe": "xxe",
    "xml-external-entity": "xxe",
    "xml_external_entity": "xxe",
    "xml-parser": "xxe",
    "xml-parse": "xxe",
    "lxml": "xxe",
    "element-tree": "xxe",
    "etree": "xxe",
    "sax": "xxe",
    "dom": "xxe",
    "minidom": "xxe",
    "expat": "xxe",
    "defusedxml": "xxe",
    "insecure-deserialization": "insecure_deserialization",
    "insecure_deserialization": "insecure_deserialization",
    "pickle": "insecure_deserialization",
    "pickle-deserialization": "insecure_deserialization",
    "yaml": "insecure_deserialization",
    "yaml-load": "insecure_deserialization",
    "yaml.load": "insecure_deserialization",
    "yaml-serialize": "insecure_deserialization",
    "marshal": "insecure_deserialization",
    "shelve": "insecure_deserialization",
    "jsonpickle": "insecure_deserialization",
    "pyyaml": "insecure_deserialization",
    "open-redirect": "open_redirect",
    "open_redirect": "open_redirect",
    "redirect": "open_redirect",
    "url-redirect": "open_redirect",
    "dangerous-redirect": "open_redirect",
    "redirect-forward": "open_redirect",
    "prototype-pollution": "prototype_pollution",
    "prototype_pollution": "prototype_pollution",
    "prototype": "prototype_pollution",
    "proto-pollution": "prototype_pollution",
    "proto_pollution": "prototype_pollution",
    "merge": "prototype_pollution",
    "object-merge": "prototype_pollution",
    "assign": "prototype_pollution",
    "object-assign": "prototype_pollution",
    "eval": "command_injection",
    "node-eval": "command_injection",
    "function-constructor": "command_injection",
    "dangerous-eval": "command_injection",
    "regex": "code_flaw",
    "reject-race": "code_flaw",
    "race-condition": "code_flaw",
    "race_condition": "code_flaw",
    "timing-attack": "code_flaw",
    "timing_attack": "code_flaw",
    "crypto": "code_flaw",
    "weak-crypto": "code_flaw",
    "weak-cipher": "code_flaw",
    "md5": "code_flaw",
    "sha1": "code_flaw",
    "des": "code_flaw",
    "rc4": "code_flaw",
    "insecure-hash": "code_flaw",
    "insecure-cipher": "code_flaw",
    "jwt-null": "code_flaw",
    "jwt-none": "code_flaw",
    "jwt-null-algorithm": "code_flaw",
    "jwt-hardcoded": "hardcoded_secret",
    "cors": "code_flaw",
    "cors-wildcard": "code_flaw",
    "helmet": "code_flaw",
    "nosniff": "code_flaw",
    "xss-protection": "code_flaw",
    "content-type": "code_flaw",
    "mime-sniff": "code_flaw",
    "assert": "code_flaw",
    "assert-statement": "code_flaw",
    "assert-safety": "code_flaw",
    "input": "code_flaw",
    "input-py2": "code_flaw",
    "dangerous-input": "code_flaw",
    "exec": "command_injection",
    "exec-used": "command_injection",
    "eval-used": "command_injection",
    "compile": "command_injection",
    "dangerous-function": "code_flaw",
    "dangerous-builtin": "code_flaw",
    "import": "code_flaw",
    "wildcard-import": "code_flaw",
    "import-star": "code_flaw",
    "relative-import": "code_flaw",
    "try-except": "code_flaw",
    "bare-except": "code_flaw",
    "broad-except": "code_flaw",
    "pass": "code_flaw",
    "pass-statement": "code_flaw",
    "exit": "code_flaw",
    "sys-exit": "code_flaw",
    "os-exit": "code_flaw",
    "html": "default",
    "html-template": "xss",
    "form": "xss",
    "input-tag": "xss",
    "script-tag": "xss",
    "on-event": "xss",
    "onclick": "xss",
    "onload": "xss",
    "onerror": "xss",
    "dangerous-tag": "xss",
    "dangerous-attribute": "xss",
    "iframe": "xss",
    "embed": "xss",
    "object-tag": "xss",
    "meta-tag": "xss",
    "meta-refresh": "xss",
    "anchor": "xss",
    "link-tag": "xss",
    "security": "default",
    "audit": "default",
    "best-practice": "default",
    "performance": "default",
    "maintainability": "default",
    "correctness": "default",
    "error-prone": "default",
    "security-audit": "default",
}
